CREATE OR REPLACE TRIGGER students_fk_check
BEFORE INSERT OR UPDATE OF GROUP_ID ON STUDENTS
FOR EACH ROW
WHEN (NEW.GROUP_ID IS NOT NULL)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM GROUPS
    WHERE ID = :NEW.GROUP_ID;
    
    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Referenced group with ID ' || :NEW.GROUP_ID || ' does not exist');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER groups_cascade_delete
BEFORE DELETE ON GROUPS
FOR EACH ROW
BEGIN
    DELETE FROM STUDENTS
    WHERE GROUP_ID = :OLD.ID;
END;
/